---
namespace: hazelcast-cluster

stack:
  defines: process-group
  metadata:
    name: hazelcast
    shortname: Hazelcast
    description: |
      Hazelcast is an open-source, distributed, in-memory data grid (IMDG) solution that provides highly scalable and fault-tolerant data processing capabilities. 
      It is designed to distribute data across multiple nodes in a cluster, allowing applications to easily scale horizontally and process large amounts of data in parallel. 
      Hazelcast provides distributed data structures and APIs for caching, distributed computing, event processing, and messaging, making it suitable for a wide range of use cases, including caching, real-time analytics, financial services, gaming, e-commerce, and more.
    tags: self hosted, distributed systems, NoSQL database, In-memory data grid, Replication and synchronization
    website: https://hazelcast.com/
    source: https://github.com/hazelcast/hazelcast
    publisher: monk.io
    icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuuCdurGuGFoZOMtq833yOm6bBc4halKidOw6vrhSoF8VW2BBFxEZ4-3PowWsjpG39_lM&usqp=CAU
  runnable-list:
    - hazelcast-cluster/hazelcast-1
    - hazelcast-cluster/hazelcast-2
    - hazelcast-cluster/hazelcast-3
    - hazelcast-cluster/hazelcast-management
  variables:
    hazelcast-management-image-tag: latest
    hazelcast-image-tag: 5.2.1
    cluster-name: hazelcast-cluster
